# Generated by Django 5.0.1 on 2024-02-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="yazilar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yaziAdi", models.CharField(max_length=50)),
                ("yaziAltBaslik", models.CharField(max_length=30)),
                ("yaziAciklama", models.TextField(verbose_name="aciklama")),
            ],
        ),
    ]
