# Generated by Django 5.0.1 on 2024-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tcore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yazilar",
            name="yaziFotosu",
            field=models.FileField(default=1, upload_to="resimler/"),
            preserve_default=False,
        ),
    ]
