# Generated by Django 5.0.1 on 2024-02-10 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tcore", "0002_yazilar_yazifotosu"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="yazilar",
            new_name="YazilarModels",
        ),
    ]
